# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ccf2a6eb6d43194c5e4c835cb0761c716edcefb8b1a73eadbc9e97a5c87b955e4217f4558ab28faf7fc85789b66ffbdd2f3003b3a6223fd51d834d0d49d773c

test:
  secret_key_base: e9c2aa8acfa9a9732e996964534597d4587fca3d70234855ff49de198e296f3f4967428f1138ef2b38c296bbeb30e39178a652cef15be8d8122743ec993ec2a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
